SUPABASE_URL = "https://qpbuwemwuygteetudvcg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwYnV3ZW13dXlndGVldHVkdmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MjE2MzUsImV4cCI6MjA3OTA5NzYzNX0.Xg0RF_JZagGzTVHaqBuNRX5EU95Z7GTB_rbFw3obMKk"
